services:
  ########################
  # RENDERERS            #
  ########################
  validaide.highcharts.renderer.graph:
    class: Validaide\HighChartsBundle\Templating\Renderer\GraphRenderer

  validaide.highcharts.renderer.image:
    class: Validaide\HighChartsBundle\Templating\Renderer\ImageRenderer
    arguments:
     - '%export_service%'


  ########################
  # HELPERS              #
  ########################
  validaide.highcharts.helper.graph:
    class:  Validaide\HighChartsBundle\Templating\Helper\GraphHelper
    arguments:
      - '@validaide.highcharts.renderer.graph'

  ########################
  # TWIG EXTENSIONS      #
  ########################
  validaide.highcharts.twig_extension.highcharts:
    class:  Validaide\HighChartsBundle\Twig\HighChartsExtension
    arguments:
      - '@validaide.highcharts.helper.graph'
      - '@validaide.highcharts.renderer.image'
    tags:
      - { name: twig.extension }

