services:
  ########################
  # RENDERERS            #
  ########################

  Validaide\HighChartsBundle\Templating\Renderer\GraphRenderer: ~

  Validaide\HighChartsBundle\Templating\Renderer\ImageRenderer: ~

  ########################
  # HELPERS              #
  ########################

  Validaide\HighChartsBundle\Templating\Helper\GraphHelper:
    arguments:
      - '@Validaide\HighChartsBundle\Templating\Renderer\GraphRenderer'

  ########################
  # TWIG EXTENSIONS      #
  ########################

  Validaide\HighChartsBundle\Twig\HighChartsExtension:
    arguments:
      - '@Validaide\HighChartsBundle\Templating\Helper\GraphHelper'
      - '@Validaide\HighChartsBundle\Templating\Renderer\ImageRenderer'
    tags:
      - { name: twig.extension }
