services:
  ########################
  # HELPERS              #
  ########################
  validaide.highcharts.helper.graph:
    class:  Validaide\HighChartsBundle\Templating\Helper\GraphHelper

  ########################
  # TWIG EXTENSIONS      #
  ########################
  validaide.highcharts.twig_extension.highcharts:
    class:  Validaide\HighChartsBundle\Twig\HighChartsExtension
    arguments:
      - '@validaide.highcharts.helper.graph'
    tags:
      - { name: twig.extension }
