services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  ########################
  # HELPERS              #
  ########################

  Validaide\HighChartsBundle\Templating\:
    resource: '../../Templating/*'

  ########################
  # TWIG EXTENSIONS      #
  ########################

  Validaide\HighChartsBundle\Twig\:
    resource: '../../Twig/*'
    tags:
      - { name: twig.extension }

