services:
  _defaults:
    autowire: true
    autoconfigure: true

  ########################
  # FORMATTER            #
  ########################

  Validaide\HighChartsBundle\Templating\Formatter\Formatter:

  ########################
  # RENDERERS            #
  ########################

  Validaide\HighChartsBundle\Templating\Renderer\GraphRenderer:
    public: true

  ########################
  # HELPERS              #
  ########################

  Validaide\HighChartsBundle\Templating\Helper\GraphHelper:

  ########################
  # TWIG EXTENSIONS      #
  ########################

  Validaide\HighChartsBundle\Twig\HighChartsExtension:
    tags:
      - { name: twig.extension }
