name: Build & Test Library
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        operating-system: [ubuntu-latest]
        php-versions: ['8.1']
    name: PHP ${{ matrix.php-versions }} Test on ${{ matrix.operating-system }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          tools: composer:v2,phpstan
        env:
          COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install PHP Dependencies
        run: composer install --optimize-autoloader --prefer-dist
        env:
          COMPOSER_AUTH: '{"github-oauth": {"github.com": "${{secrets.COMPOSER_GITHUB_ACTIONS }}"} }'
          SYMFONY_ENV: test

# TODO: We can only run the tests if we have the highcharts-export-server installed and available to the CLI
#      - name: Unit Tests
#        run: vendor/bin/phpunit

      - name: Static Analysis (phpstan)
        run: phpstan analyse --memory-limit=-1 --no-progress